### ISSUE TITLE
Add age to bios

### ISSUE THREAD

**Issue by carlosmertens** [EugeneeT/short-bio#1]
The exercise requests name and age, please add age :)

**Comment by EugeneeT** [comment]
ok !

**Comment by micah-anderson** [comment]
I'm done too you guys. Have a great rest of you vacations :palm_tree: :+1:

**Comment by carlosmertens** [comment]
Well done team! You guys are awesome!

**Comment by micah-anderson** [comment]
You're awesome too Carlo's! :100:
